### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by M4dGun** [MatMoul/plasma-containmentactions-customdesktopmenu#1]
How can I restore my previous config?
Even if I run "sudo make uninstall" and "logout/login", on  mouse's right click there's still custom-desktop-menu.

**Comment by MatMoul** [comment]
Uninstall is not implemented.

To reset your right click :
Edit the file ~/.config/plasma-org.kde.plasma.desktop-appletsrc
[ActionPlugins][0]
RightButton;NoModifier=org.kde.contextmenu

To remove this package, delete the next two files :
/usr/lib/qt/plugins/plasma_containmentactions_customdesktopmenu.so
/usr/local/share/kservices5/plasma-containmentactions-customdesktopmenu.desktop
