### ISSUE TITLE
Need help with packaging

### ISSUE THREAD

**Issue by hazel-bunny** [MatMoul/plasma-containmentactions-customdesktopmenu#5]
I'm trying to package this menu for Fedora 40 and above in [my copr](https://copr.fedorainfracloud.org/coprs/hazel-bunny/ricing). The [source rpm](https://download.copr.fedorainfracloud.org/results/hazel-bunny/ricing/fedora-40-x86_64/07615706-plasma-custom-desktop-menu/plasma-custom-desktop-menu-0.2.0-1.20240309gitbc699db.fc40.src.rpm) contains the tarball and the spec file. The [built rpm](https://download.copr.fedorainfracloud.org/results/hazel-bunny/ricing/fedora-40-x86_64/07615706-plasma-custom-desktop-menu/plasma-custom-desktop-menu-0.2.0-1.20240309gitbc699db.fc40.x86_64.rpm) seems to only include the shared object named matmoul-customdesktopmenu.so along with the license and the README file. Is there anything else that needs to be included?

**Comment by MatMoul** [comment]
I confirm, this app contain only the license file and the matmoul-customdesktopmenu.so file that  is the addon.
